SRCDIR = ${HTHETA}/src/
OBJDIR = ${HTHETA}/bin/objects/
FC     = nvfortran
OPTS_F = -O3 -acc=multicore -module $(OBJDIR) # -xHost -mcmodel medium -shared-intel -warn all -warn noexternals
OPTS_OMP =

LIBLIST  = -lnvToolsExt   # -L${NVHPC_HOME}/Linux_x86_64/22.3/cuda/lib64/
INCLIST  = 

PROG = ${HTHETA}/bin/htheta.exe

main           = ${OBJDIR}/main

OBJC = $(main).o

all :: HTHETA

HTHETA: $(OBJC)
	$(FC) $(OPTS_F) $(OBJC) $(OPTS_OMP) ${LIBLIST} -o $(PROG)

clean: 
	rm -f $(SRCDIR)/*.optrpt $(OBJDIR)/*.o $(OBJDIR)/*.mod

$(main).o: ${SRCDIR}/main.F90
	$(FC) $(OPTS_F) $(OPTS_OMP) $(INCLIST) -c $< -o $@